/**
 * Report templates for SOC 2 audit evidence reports.
 *
 * Provides professional formatting templates for HTML, Markdown, and JSON exports.
 */

import type {
  SOC2Report,
  ControlObjective,
  ControlTest,
  Evidence,
  ComplianceStatus,
  TrustServiceCategory,
} from './types';

// ---------------------------------------------------------------------------
// Status helpers
// ---------------------------------------------------------------------------

const STATUS_LABELS: Record<ComplianceStatus, string> = {
  effective: 'Effective',
  effective_with_exceptions: 'Effective with Exceptions',
  not_effective: 'Not Effective',
  not_tested: 'Not Tested',
  not_applicable: 'Not Applicable',
};

const STATUS_COLORS: Record<ComplianceStatus, string> = {
  effective: '#22c55e',
  effective_with_exceptions: '#f59e0b',
  not_effective: '#ef4444',
  not_tested: '#94a3b8',
  not_applicable: '#64748b',
};

const CATEGORY_LABELS: Record<TrustServiceCategory, string> = {
  security: 'Security',
  availability: 'Availability',
  processing_integrity: 'Processing Integrity',
  confidentiality: 'Confidentiality',
  privacy: 'Privacy',
};

export function getStatusLabel(status: ComplianceStatus): string {
  return STATUS_LABELS[status];
}

export function getCategoryLabel(category: TrustServiceCategory): string {
  return CATEGORY_LABELS[category];
}

// ---------------------------------------------------------------------------
// Markdown templates
// ---------------------------------------------------------------------------

export function renderMarkdownReport(report: SOC2Report): string {
  const lines: string[] = [];

  lines.push(`# ${report.title}`);
  lines.push('');
  lines.push(`**Organization:** ${report.organizationName}`);
  lines.push(`**Report ID:** ${report.id}`);
  lines.push(`**Generated:** ${report.generatedAt}`);
  lines.push(`**Audit Period:** ${report.auditPeriod.startDate} to ${report.auditPeriod.endDate}`);
  lines.push(`**Overall Status:** ${getStatusLabel(report.overallStatus)}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Executive Summary
  lines.push('## 1. Executive Summary');
  lines.push('');
  lines.push(renderMarkdownExecutiveSummary(report));
  lines.push('');

  // System Description
  lines.push('## 2. System Description');
  lines.push('');
  lines.push(report.systemDescription);
  lines.push('');

  // Trust Service Categories
  lines.push('## 3. Trust Service Categories');
  lines.push('');
  const categories = groupControlsByCategory(report.controls);
  let sectionNum = 1;
  for (const [category, controls] of Object.entries(categories)) {
    lines.push(`### 3.${sectionNum}. ${getCategoryLabel(category as TrustServiceCategory)}`);
    lines.push('');
    for (const control of controls) {
      lines.push(renderMarkdownControl(control, report.controlTests));
    }
    sectionNum++;
  }

  // Exceptions
  if (report.exceptions.length > 0) {
    lines.push('## 4. Exceptions and Remediation');
    lines.push('');
    for (const exception of report.exceptions) {
      lines.push(`### ${exception.controlId}`);
      lines.push('');
      lines.push(`**Description:** ${exception.description}`);
      lines.push('');
      lines.push(`**Remediation:** ${exception.remediation}`);
      if (exception.remediationDate) {
        lines.push(`**Target Date:** ${exception.remediationDate}`);
      }
      lines.push('');
    }
  }

  // Custom sections
  for (const section of report.sections) {
    lines.push(`## ${section.title}`);
    lines.push('');
    lines.push(section.content);
    lines.push('');
    if (section.subsections) {
      for (const sub of section.subsections) {
        lines.push(`### ${sub.title}`);
        lines.push('');
        lines.push(sub.content);
        lines.push('');
      }
    }
  }

  lines.push('---');
  lines.push(`*Report generated by @aicofounder/soc2 v${report.version}*`);

  return lines.join('\n');
}

function renderMarkdownExecutiveSummary(report: SOC2Report): string {
  const totalControls = report.controls.length;
  const effective = report.controls.filter((c) => c.status === 'effective').length;
  const withExceptions = report.controls.filter(
    (c) => c.status === 'effective_with_exceptions'
  ).length;
  const notEffective = report.controls.filter((c) => c.status === 'not_effective').length;

  const lines: string[] = [];
  lines.push(
    `This SOC 2 Type II report covers the ${report.organizationName} AI guardrail system ` +
    `for the period ${report.auditPeriod.startDate} to ${report.auditPeriod.endDate}.`
  );
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Controls | ${totalControls} |`);
  lines.push(`| Effective | ${effective} |`);
  lines.push(`| Effective with Exceptions | ${withExceptions} |`);
  lines.push(`| Not Effective | ${notEffective} |`);
  lines.push(`| Trust Service Categories | ${report.trustServiceCategories.map(getCategoryLabel).join(', ')} |`);
  lines.push(`| Exceptions | ${report.exceptions.length} |`);

  return lines.join('\n');
}

function renderMarkdownControl(control: ControlObjective, tests: ControlTest[]): string {
  const lines: string[] = [];
  const statusLabel = getStatusLabel(control.status);

  lines.push(`#### ${control.id}: ${control.title}`);
  lines.push('');
  lines.push(`**Status:** ${statusLabel}`);
  lines.push('');
  lines.push(`**Description:** ${control.description}`);
  lines.push('');
  lines.push(`**CoFounder Mapping:** ${control.cofounderMapping.join(', ')}`);
  lines.push('');

  if (control.notes) {
    lines.push(`> ${control.notes}`);
    lines.push('');
  }

  // Associated tests
  const controlTests = tests.filter((t) => t.controlId === control.id);
  if (controlTests.length > 0) {
    lines.push('**Test Results:**');
    lines.push('');
    for (const test of controlTests) {
      const icon = test.result.passed ? 'PASS' : 'FAIL';
      lines.push(`- [${icon}] ${test.testDescription}`);
      lines.push(`  - ${test.result.details}`);
      if (test.result.exceptionsFound) {
        lines.push(`  - Exceptions found: ${test.result.exceptionsFound}`);
      }
    }
    lines.push('');
  }

  // Evidence
  if (control.evidence.length > 0) {
    lines.push('**Evidence:**');
    lines.push('');
    for (const ev of control.evidence) {
      lines.push(`- **${ev.title}** (${ev.type}, ${ev.source})`);
      lines.push(`  ${ev.description}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// HTML templates
// ---------------------------------------------------------------------------

export function renderHTMLReport(report: SOC2Report): string {
  const categories = groupControlsByCategory(report.controls);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(report.title)}</title>
<style>
  :root { --primary: #1e293b; --accent: #3b82f6; --bg: #ffffff; --border: #e2e8f0; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: var(--primary); line-height: 1.6; max-width: 1000px; margin: 0 auto; padding: 40px 20px; }
  h1 { font-size: 28px; margin-bottom: 8px; }
  h2 { font-size: 22px; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 2px solid var(--accent); }
  h3 { font-size: 18px; margin: 24px 0 12px; }
  h4 { font-size: 15px; margin: 16px 0 8px; }
  p { margin-bottom: 12px; }
  .meta { color: #64748b; font-size: 14px; margin-bottom: 4px; }
  .status-badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 13px; font-weight: 600; color: #fff; }
  .overall-status { font-size: 16px; padding: 4px 16px; margin-top: 8px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { padding: 10px 14px; text-align: left; border: 1px solid var(--border); }
  th { background: #f8fafc; font-weight: 600; }
  .control-card { border: 1px solid var(--border); border-radius: 8px; padding: 16px; margin-bottom: 16px; }
  .control-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
  .evidence-list { list-style: none; padding: 0; }
  .evidence-list li { padding: 8px 12px; border-left: 3px solid var(--accent); margin-bottom: 8px; background: #f8fafc; }
  .test-result { padding: 8px 12px; margin: 4px 0; border-radius: 4px; }
  .test-pass { background: #f0fdf4; border-left: 3px solid #22c55e; }
  .test-fail { background: #fef2f2; border-left: 3px solid #ef4444; }
  .exception { background: #fffbeb; border: 1px solid #f59e0b; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--border); color: #94a3b8; font-size: 13px; }
  hr { border: none; border-top: 1px solid var(--border); margin: 24px 0; }
</style>
</head>
<body>
<h1>${escapeHtml(report.title)}</h1>
<p class="meta"><strong>Organization:</strong> ${escapeHtml(report.organizationName)}</p>
<p class="meta"><strong>Report ID:</strong> ${escapeHtml(report.id)}</p>
<p class="meta"><strong>Generated:</strong> ${escapeHtml(report.generatedAt)}</p>
<p class="meta"><strong>Audit Period:</strong> ${escapeHtml(report.auditPeriod.startDate)} to ${escapeHtml(report.auditPeriod.endDate)}</p>
<span class="status-badge overall-status" style="background:${STATUS_COLORS[report.overallStatus]}">${getStatusLabel(report.overallStatus)}</span>

<hr>

<h2>1. Executive Summary</h2>
${renderHTMLExecutiveSummary(report)}

<h2>2. System Description</h2>
<p>${escapeHtml(report.systemDescription)}</p>

<h2>3. Trust Service Categories</h2>
${Object.entries(categories)
  .map(
    ([cat, controls], i) => `
<h3>3.${i + 1}. ${getCategoryLabel(cat as TrustServiceCategory)}</h3>
${controls.map((c) => renderHTMLControl(c, report.controlTests)).join('\n')}`
  )
  .join('\n')}

${
  report.exceptions.length > 0
    ? `<h2>4. Exceptions and Remediation</h2>
${report.exceptions
  .map(
    (ex) => `
<div class="exception">
  <h4>${escapeHtml(ex.controlId)}</h4>
  <p><strong>Description:</strong> ${escapeHtml(ex.description)}</p>
  <p><strong>Remediation:</strong> ${escapeHtml(ex.remediation)}</p>
  ${ex.remediationDate ? `<p><strong>Target Date:</strong> ${escapeHtml(ex.remediationDate)}</p>` : ''}
</div>`
  )
  .join('\n')}`
    : ''
}

${report.sections
  .map(
    (s) => `
<h2>${escapeHtml(s.title)}</h2>
<p>${escapeHtml(s.content)}</p>
${(s.subsections || []).map((sub) => `<h3>${escapeHtml(sub.title)}</h3><p>${escapeHtml(sub.content)}</p>`).join('\n')}`
  )
  .join('\n')}

<div class="footer">
  <p>Report generated by @aicofounder/soc2 v${escapeHtml(report.version)}</p>
</div>
</body>
</html>`;
}

function renderHTMLExecutiveSummary(report: SOC2Report): string {
  const total = report.controls.length;
  const effective = report.controls.filter((c) => c.status === 'effective').length;
  const withExceptions = report.controls.filter((c) => c.status === 'effective_with_exceptions').length;
  const notEffective = report.controls.filter((c) => c.status === 'not_effective').length;

  return `
<p>This SOC 2 Type II report covers the ${escapeHtml(report.organizationName)} AI guardrail system
for the period ${escapeHtml(report.auditPeriod.startDate)} to ${escapeHtml(report.auditPeriod.endDate)}.</p>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Total Controls</td><td>${total}</td></tr>
  <tr><td>Effective</td><td>${effective}</td></tr>
  <tr><td>Effective with Exceptions</td><td>${withExceptions}</td></tr>
  <tr><td>Not Effective</td><td>${notEffective}</td></tr>
  <tr><td>Trust Service Categories</td><td>${report.trustServiceCategories.map(getCategoryLabel).join(', ')}</td></tr>
  <tr><td>Exceptions</td><td>${report.exceptions.length}</td></tr>
</table>`;
}

function renderHTMLControl(control: ControlObjective, tests: ControlTest[]): string {
  const controlTests = tests.filter((t) => t.controlId === control.id);
  return `
<div class="control-card">
  <div class="control-header">
    <h4>${escapeHtml(control.id)}: ${escapeHtml(control.title)}</h4>
    <span class="status-badge" style="background:${STATUS_COLORS[control.status]}">${getStatusLabel(control.status)}</span>
  </div>
  <p>${escapeHtml(control.description)}</p>
  <p><strong>CoFounder Mapping:</strong> ${control.cofounderMapping.map(escapeHtml).join(', ')}</p>
  ${control.notes ? `<p><em>${escapeHtml(control.notes)}</em></p>` : ''}
  ${
    controlTests.length > 0
      ? `<h4>Test Results</h4>
  ${controlTests
    .map(
      (t) => `
  <div class="test-result ${t.result.passed ? 'test-pass' : 'test-fail'}">
    <strong>${t.result.passed ? 'PASS' : 'FAIL'}:</strong> ${escapeHtml(t.testDescription)}<br>
    <span>${escapeHtml(t.result.details)}</span>
    ${t.result.exceptionsFound ? `<br><em>Exceptions: ${t.result.exceptionsFound}</em>` : ''}
  </div>`
    )
    .join('\n')}`
      : ''
  }
  ${
    control.evidence.length > 0
      ? `<h4>Evidence</h4>
  <ul class="evidence-list">
    ${control.evidence
      .map(
        (ev) =>
          `<li><strong>${escapeHtml(ev.title)}</strong> (${escapeHtml(ev.type)}, ${escapeHtml(ev.source)})<br>${escapeHtml(ev.description)}</li>`
      )
      .join('\n')}
  </ul>`
      : ''
  }
</div>`;
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function groupControlsByCategory(
  controls: ControlObjective[]
): Record<string, ControlObjective[]> {
  const grouped: Record<string, ControlObjective[]> = {};
  for (const control of controls) {
    if (!grouped[control.category]) {
      grouped[control.category] = [];
    }
    grouped[control.category].push(control);
  }
  return grouped;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Render evidence as a standalone markdown section. */
export function renderEvidenceMarkdown(evidence: Evidence[]): string {
  if (evidence.length === 0) return '_No evidence collected._';

  const lines: string[] = [];
  for (const ev of evidence) {
    lines.push(`### ${ev.title}`);
    lines.push('');
    lines.push(`- **Type:** ${ev.type}`);
    lines.push(`- **Source:** ${ev.source}`);
    lines.push(`- **Collected:** ${ev.collectedAt}`);
    lines.push(`- **Description:** ${ev.description}`);
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(ev.data, null, 2));
    lines.push('```');
    lines.push('');
  }
  return lines.join('\n');
}
