packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples/rana-ui-example'
  - '!examples/rag-app'
  - '!examples/react-typescript'
  - '!examples/chatbot'
  - '!examples/multi-agent'
  - '!examples/sdk-demo'
