# RANA Configuration File
# Version: 2.0
# Template: Next.js + Supabase

version: '2.0'
name: 'RANA Next.js + Supabase Template'

# Project metadata
project:
  name: 'my-aads-app'
  description: 'Production-ready app built with RANA'
  version: '1.0.0'
  author: 'Your Name'

# Tech stack
stack:
  framework: 'nextjs'
  version: '14.1.0'
  typescript: true
  database: 'supabase'
  auth: 'supabase'
  styling: 'tailwind'

# Framework configuration
frameworks:
  database:
    enabled: true
    provider: 'supabase'
    rls: true
    migrations: true

  security:
    enabled: true
    auth:
      provider: 'supabase'
      strategies: ['email', 'oauth']
      oauthProviders: ['google', 'github']
    rateLimit:
      enabled: true
      provider: 'upstash'
      maxRequests: 100
      windowMs: 60000
    headers:
      csp: true
      hsts: true
      xFrame: 'DENY'

  llm:
    enabled: true
    providers:
      - name: 'openai'
        models: ['gpt-4-turbo-preview', 'gpt-3.5-turbo']
      - name: 'anthropic'
        models: ['claude-3-5-sonnet-20241022', 'claude-3-haiku-20240307']
    optimization:
      caching: true
      cacheProvider: 'upstash'
      cacheTTL: 3600
      modelSelection: 'auto'
      promptOptimization: true

  seo:
    enabled: true
    sitemap: true
    robotsTxt: true
    manifest: true
    structuredData: true
    metaTags:
      default:
        title: 'My RANA App'
        description: 'Built with RANA Framework'
        image: '/og-image.png'

  mobile:
    enabled: true
    touchTargets: 44 # minimum size in px
    viewport: true
    pwa: true
    gestures: true
    responsive: true

# Quality gates
quality:
  minSecurityScore: 90
  minSEOScore: 85
  minMobileScore: 90
  minTestCoverage: 80
  maxLLMCost: 500 # monthly in USD

# Pre-deployment checks
checks:
  - name: 'RANA Compliance'
    command: 'aads check'
    required: true

  - name: 'Security Audit'
    command: 'aads security:audit'
    required: true

  - name: 'SEO Validation'
    command: 'aads seo:check'
    required: true

  - name: 'Mobile Validation'
    command: 'aads mobile:validate'
    required: true

  - name: 'LLM Cost Analysis'
    command: 'aads llm:analyze'
    required: false

  - name: 'Tests'
    command: 'npm run test'
    required: true

  - name: 'Build'
    command: 'npm run build'
    required: true

# Deployment configuration
deployment:
  platform: 'vercel'
  autoDeployment: true
  preDeployChecks: true
  environments:
    - name: 'production'
      branch: 'main'
      url: 'https://example.com'
    - name: 'staging'
      branch: 'develop'
      url: 'https://staging.example.com'

# Environment variables (names only, not values)
env:
  required:
    - NEXT_PUBLIC_SUPABASE_URL
    - NEXT_PUBLIC_SUPABASE_ANON_KEY
    - SUPABASE_SERVICE_ROLE_KEY
    - NEXT_PUBLIC_SITE_URL
    - NEXT_PUBLIC_SITE_NAME
  optional:
    - OPENAI_API_KEY
    - ANTHROPIC_API_KEY
    - XAI_API_KEY
    - GOOGLE_API_KEY
    - UPSTASH_REDIS_URL
    - UPSTASH_REDIS_TOKEN
    - RESEND_API_KEY
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET

# Development settings
development:
  port: 3000
  hotReload: true
  sourceMap: true

# Build settings
build:
  outputDir: '.next'
  minify: true
  sourceMaps: false

# Testing
testing:
  framework: 'jest'
  coverage:
    enabled: true
    threshold: 80
  e2e:
    framework: 'playwright'

# Code quality
codeQuality:
  linter: 'eslint'
  formatter: 'prettier'
  typeCheck: true

# Git hooks
hooks:
  preCommit:
    - 'npm run lint'
    - 'npm run test'
  prePush:
    - 'npx aads check'
    - 'npx aads security:audit'

# Monitoring (optional)
monitoring:
  enabled: false
  provider: 'vercel-analytics'

# Analytics (optional)
analytics:
  enabled: false
  provider: 'vercel-analytics'
